### ISSUE TITLE
Error messages could't show Chinese correctly in Windows

### ISSUE THREAD

**Issue by 598753468** [Gimly/vscode-matlab#16]
I installed Matlab in Chinese Language. Error messages are like this:
![](https://goo.gl/photos/XXmp11gVt8rHSnkg9)
![1959868603](https://user-images.githubusercontent.com/7996337/27567357-d094c60e-5b1d-11e7-8529-5c4504512e7b.jpg)

**Comment by hexiaoqiu** [comment]
Actually, I am using the English version windows 10 and installed English version Matlab.
Furthermore, the VS code I also used a English version. 
But!!!! I get the Error messages from matlab full of messy code. I am a Chinese user in China mainland.
Would you please help me?

**Comment by Gimly** [comment]
That's very strange. Could you please give a screenshot of the issue? Maybe also the file where the issue arise if that's possible.
Thanks

**Comment by hexiaoqiu** [comment]
@Gimly Here is the screenshot, Thank your time and attention to this issue.
Your work is excellent and facilitate my work everyday.

![2017-08-31 2](https://user-images.githubusercontent.com/18747654/29915945-e994aebe-8e6f-11e7-85f2-acbe13b5e222.png)

**Comment by planewave** [comment]
It is an encoding problem.
add `"files.encoding": "gb2312",` in your _settings.json_ file and it will work

**Comment by Gimly** [comment]
@planewave It is definitely an encoding issue, but it's on the linter side. Are you sure that modifying the file encoding will actually do something to @hexiaoqiu's issue?

If that's the case, could you please test, @hexiaoqiu and tell us. Your issue is really complicated to test. Thanks in advance for your help.

**Comment by hexiaoqiu** [comment]
@Gimly 
![tim 20170919113859](https://user-images.githubusercontent.com/18747654/30574853-6a473220-9d2f-11e7-9512-7f169506002d.png)
@planewave Not work...

**Comment by hexiaoqiu** [comment]
My opinion is that the Matlab do pass the debug info to VS Code. but the info is adapting different code method with what VS Code used.

**Comment by planewave** [comment]
@hexiaoqiu If your .m file is encoded with GB2312, my setting will show Chinese correctly.
but you are receiving debug info from Matlab, wait a second, you can debug Matlab code with vs code?
How to do that?
I thought it is just for coding or viewing.

**Comment by Gimly** [comment]
@planewave He means the linting information, which shows the error message and so on. I'm calling a Matlab utility (the one you have to configure the path for). I'm sending it the source code and I'm receiving in return a file with a specific structure that returns all the errors and remarks.

**Comment by hexiaoqiu** [comment]
@planewave It's just linting information. Should I change the code method for my .m files? Thanks~

**Comment by planewave** [comment]
@hexiaoqiu If your .m file is encoded in GB2312, changing the encoding of vs code can let it display Chinese (in you file) correctly.
But not sure about the encoding of linting information...

**Comment by psychelzh** [comment]
Here I have the same issue. But notably, when I changed my language settings of `MATLAB` to English, I can see English lintings in my `MATLAB editor`. I think there must be a way to display all the message to English, too. 

Looking forward to solving this issue.

**Comment by hongkai98** [comment]
Same here! And I would like to provide some more info on this: 

I've been using this extension long. Under the same OS ( Win10), m-lint warnings worked well in the old days with code v0.x ~ v1.0x, though I could not recall exactly whether it displayed chinese or all english correctly. Yet one thing I do remember clearly is that, when i made an update of code to v1.1( or v1.2) , the m-lint warnings suddenly went into a mess like what you guys showed above. 

Hope this could help you guys find something useful. Looking forward to the breakthrough! Thanks.

**Comment by Gimly** [comment]
@hongkai98 Thanks for that info, it might definitely be useful. It could mean that something change in Code's API which causes the issue. I finally have a bit of free time to give that extension some love and will try to fix that issue.

The biggest challenge is to reproduce it, I don't really have access to a Chinese computer and even if I could install a VM, I don't have a Matlab license to install on.

I'd like to try something though, could someone who experience the issue dump the output of a call to mlint to a file and sending me the file. Please copy the file itself and not copy-paste its content, so that it keeps its original encoding.

To call mlint, open a Windows cmd and paste the path to the mlint executable followed by a path to a matlab file.

```
C:\pathToMatlab\mlint.exe C:\test\test.m > sampleMlint.txt
```

In the meantime, I'm going to check other extensions to see if I can figure out how they dealt with that issue.

**Comment by hongkai98** [comment]
@Gimly I'd love to help.

I've tried to dump the results into the txt file, but it ended up creating a empty txt file. Is it me or is there something wrong? 

![faileddump](https://user-images.githubusercontent.com/1357113/30957853-f869c1ae-a46d-11e7-8942-3a62b6ef3827.png)

**Comment by Gimly** [comment]
@hongkai98 My bad, I think that mlint sends the linting infos to stderr and not stdout. Could you do that again but instead of piping through `>` you pipe with `&>`.

Sot it will be:
`C:\pathToMatlab\mlint.exe C:\test\test.m &> sampleMlint.txt`

Thanks a lot for your help.

**Comment by hongkai98** [comment]
@Gimly lol &> still not works but I finally made it with a little help with google :)

![done](https://user-images.githubusercontent.com/1357113/30959317-5a153aba-a472-11e7-9540-082e06027037.png)

[sampleMlint.txt](https://github.com/Gimly/vscode-matlab/files/1340282/sampleMlint.txt)

**Comment by Gimly** [comment]
@hongkai98 Cool, we're getting somewhere I think, if I open the file on my computer in Code it's opened in UTF-8 and obviously it fails. If you try to open it on your computer in Code, can you tell me in which encoding it's using? I'm guessing `GB 2312` (Simplified Chinese) but I want to be sure. It's the thing that I have circled on the following print screen.

![image](https://user-images.githubusercontent.com/168669/30960044-28c76102-a442-11e7-9d6d-286441bbbe4e.png)

**Comment by hongkai98** [comment]
@Gimly Either GB2312 or GBK will do.

**Comment by Gimly** [comment]
OK, what do you think would be the best approach from a user's perspective? Get Visual Studio's Code `files.encoding` setting (as @planewave suggested) and use that, get the document's file encoding directly, or add a new setting to the extension? 

Adding a new setting to the extension would allow to have a different encoding on the machine that the one used for the file, and might prevent some issues with the drawback that people have to know how to set it and which encoding is the good for their machine.

I'll check if I can do without settings, but I doubt it.

**Comment by hongkai98** [comment]
@Gimly I'm already using the first one with file.encoding set to GBK, but it doesn't seem to work for the output of M-lint (as far as i know, it only works for the content in files, without affecting the M-lint part). 

If the second choice could change the encoding of the warning output of M-lint by somehow dealing with it in the extension, i guess it would be the best.

**Comment by Gimly** [comment]
Version 0.7.0 has now the possibility to change the encoding of the linter. This should allow to fix that issue. You should go to the settings and add `"matlab.linterEncoding" : "gb2312"` for Chinese (or "gbk", not sure which is the correct one, I guess it depends on your Windows installation).

Please tell me if that works correctly, if not I'll do another update.

**Comment by hongkai98** [comment]
@Gimly Thanks for the effort! When "matlab.linterEncoding" is set to "utf8", the warning is messy as usual; but when I change it into "gb2312"( a subset of gbk) or "gbk", restart Code and make a modified save of the test file, the linter seems to have a problem, showing no warnings ( not working, like ).  
![utf8](https://user-images.githubusercontent.com/1357113/30997439-880acc2c-a4fa-11e7-9377-7853dac79380.png)
![gb2312](https://user-images.githubusercontent.com/1357113/30997468-aba641e8-a4fa-11e7-947e-20125a9aae89.png)

**Comment by psychelzh** [comment]
@hongkai98 @Gimly Here the same. I have changed the encoding to 'gb2312', and mlint seems to stop working.

**Comment by hongkai98** [comment]
@Gimly If you have access to Matlab, maybe you can try setting linterEncoding to gb2312 or gbk, to see if you can get the messy warning like us. XP

**Comment by Gimly** [comment]
@hongkai98 I'm sorry about the messup, that bug is a real pain to test, I can't figure out a good solution to test it correctly, so I have to "guess". On top of that NodeJs' documentation on `child_process` is just awful.

Good news is, I know why it doesn't show anything after setting the parameter and I fixed it. The bad news is that I'm not sure if the root of the issue is really fixed, and I don't have any way to test it.

I did a packaged version of the fix that I'm trying, if one of you guys experiencing the issue could test it, that would be really useful!

[matlab-0.7.1-beta.zip](https://github.com/Gimly/vscode-matlab/files/1343401/matlab-0.7.1-beta.zip)

To install follow those instructions: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

Hopefully this fixes the issue.

Thanks for your help.

**Comment by hongkai98** [comment]
@Gimly I've tried the beta version with "install from a vsix". It did make outputs now. Yet sad news is that with the parameter setting to "gb2312", the result is still the same as that of "utf8".  
![0 7 1beta](https://user-images.githubusercontent.com/1357113/31005681-5679e79c-a52c-11e7-887d-30079275e19a.png)

**Comment by Gimly** [comment]
This is starting to drive me crazy 😄.
I don't understand, I'm searching for similar issue with calling `child_process` but can't find any example where they had to deal with this console encoding issue.

I'll search some more. Do you by any chance have another extension in code which calls an external program and that works with the Chinese encoding?

**Comment by Gimly** [comment]
OK, I think I'm unto something, I have found a library ([iconv-lite](https://github.com/ashtuchkin/iconv-lite)) that supports gb2312 which nodejs doesn't by default.

@hongkai98 Could you try this new version of the extension? Thanks a lot for your help!
[matlab-0.7.1-beta.zip](https://github.com/Gimly/vscode-matlab/files/1343899/matlab-0.7.1-beta.zip)

**Comment by hongkai98** [comment]
@Gimly Sorry I'm currently on vacation now. I'm afraid i can't have access to pc until Oct 3rd.

**Comment by Gimly** [comment]
No worries, enjoy your vacations 😃.

If someone else has the possibility to test the version I added, it would be of great help!

**Comment by hongkai98** [comment]
@Gimly WOW! You made it! It now shows proper words! Thank you soooooooo much!

![wow](https://user-images.githubusercontent.com/1357113/31229932-ebbc9128-aa14-11e7-9898-e68ec79b94dc.png)

**Comment by psychelzh** [comment]
@hongkai98 How did you make it? Change the encoding?

**Comment by Gimly** [comment]
Don’t do anything yet, I’ve created a test version that needs to be installed manually. Now that I know that this version works, thanks to the tests made by @hongkai98, I’m going to push a new version in the marketplace.

I'll do it probably in 2-3h.

Thanks a lot @hongkai98 for your tests, you’re awesome! I’m so glad to have been able to correct that stupid bug!

De : 张亮
Envoyé le :jeudi, 5 octobre 2017 17:50
À : Gimly/vscode-matlab
Cc : Xavier Hahn; Mention
Objet :Re: [Gimly/vscode-matlab] Error messages could't show Chinesecorrectly in Windows (#16)

@hongkai98 How did you make it? Change the encoding?

**Comment by Gimly** [comment]
Issue is finally fixed in version 0.7.1! Update your extension, add the `"matlab.linterEncoding" : "gb2312"` parameter in your preferences (change according to the correct character encoding that correspond to your region, that one is for Chinese) and you should see the linting messages working in your locale.

A special thank again to @hongkai98 and @psychelzh  who took the time to help me test the versions and finally kill that bug, and to all of you who took the time to test, send the bug issue and print screens.

**Comment by jerrychong25** [comment]
Hi @Gimly,

I have followed your suggestion to `"matlab.linterEncoding" : "gb2312"` in settings.json, as per below:
![2](https://user-images.githubusercontent.com/15714095/53775675-6cec9400-3f2e-11e9-8d87-557a3ea1ac29.JPG)

However, VS Code still displays unknown characters and symbols in .m MATLAB files, as per below:
![1](https://user-images.githubusercontent.com/15714095/53775723-94dbf780-3f2e-11e9-8183-1073a8050d03.JPG)

My Windows 7 laptop default language is **English (Malaysia)**.

**VS Code Version Details**
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Could advise on this issue?

Thanks.
